
version: '3.9'

services:

  postgres:
    image: postgres:latest
    networks:
      - database
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ../migrations:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    networks:
      - kafka
    ports:
      - "9092:9092"
    hostname: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_PROCESS_ROLES:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: broker-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

  calendar:
    build:
      context: ../build
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  scheduler:
    build:
      context: ../build
      dockerfile: Dockerfile-scheduler
    networks:
      - backend
      - kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  storer:
    build:
      context: ../build
      dockerfile: Dockerfile-storer
    networks:
      - backend
      - kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  pgdata:
    driver: local

networks:
  kafka:
    driver: bridge
  backend:
    driver: bridge
