
version: '3.9'

services:

  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ../migrations:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      kafka-net:
        aliases:
          - zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    networks:
      kafka-net:
        aliases:
          - kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: broker-ui
    ports:
      - "8090:8080"
    networks:
      kafka-net:
        aliases:
          - kafkaui
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=PLAINTEXT://kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zk:2181
    links:
      - kafka
      - zookeeper

  storer:
    build:
      context: ..
      dockerfile: ./build/Dockerfile-storer
    networks:
      - backend
      - kafka-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  calendar:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  scheduler:
    build:
      context: ..
      dockerfile: ./build/Dockerfile-scheduler
    networks:
      - backend
      - kafka-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started



volumes:
  pgdata:
    driver: local

networks:
  kafka-net:
    driver: bridge
  backend:
    driver: bridge

