// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Calendar - OpenAPI 3.0
 *
 * This is a sample Calendar Server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.12
 */

package api

import (
	"context"
	"net/http"
)

// CalendarEventsAPIRouter defines the required methods for binding the api requests to a responses for the CalendarEventsAPI
// The CalendarEventsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a CalendarEventsAPIServicer to perform the required actions, then write the service results to the http response.
type CalendarEventsAPIRouter interface {
	GetCalendarEvents(http.ResponseWriter, *http.Request)
	AddCalendarEvent(http.ResponseWriter, *http.Request)
	UpdateCalendarEventById(http.ResponseWriter, *http.Request)
	DeleteCalendarEventById(http.ResponseWriter, *http.Request)
}

// CalendarEventsAPIServicer defines the api actions for the CalendarEventsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CalendarEventsAPIServicer interface {
	GetCalendarEvents(context.Context) (ImplResponse, error)
	AddCalendarEvent(context.Context, Event) (ImplResponse, error)
	UpdateCalendarEventById(context.Context, string, Event) (ImplResponse, error)
	DeleteCalendarEventById(context.Context, string) (ImplResponse, error)
}
