// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Calendar - OpenAPI 3.0
 *
 * This is a sample Calendar Server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.12
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// CalendarEventsAPIService is a service that implements the logic for the CalendarEventsAPIServicer
// This service should implement the business logic for every endpoint for the CalendarEventsAPI API.
// Include any external packages or services that will be required by this service.
type CalendarEventsAPIService struct {
}

// NewCalendarEventsAPIService creates a default api service
func NewCalendarEventsAPIService() *CalendarEventsAPIService {
	return &CalendarEventsAPIService{}
}

// GetCalendarEvents - Get all calendar events
func (s *CalendarEventsAPIService) GetCalendarEvents(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCalendarEvents with the required logic for this service method.
	// Add api_calendar_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Event{}) or use other options such as http.Ok ...
	// return Response(200, Event{}), nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	// return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCalendarEvents method not implemented")
}

// AddCalendarEvent - Add a calendar event to calendar.
func (s *CalendarEventsAPIService) AddCalendarEvent(ctx context.Context, event Event) (ImplResponse, error) {
	// TODO - update AddCalendarEvent with the required logic for this service method.
	// Add api_calendar_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Event{}) or use other options such as http.Ok ...
	// return Response(200, Event{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	// return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddCalendarEvent method not implemented")
}

// UpdateCalendarEventById - Update Calendar Event by Id.
func (s *CalendarEventsAPIService) UpdateCalendarEventById(ctx context.Context, calendarEventId string, event Event) (ImplResponse, error) {
	// TODO - update UpdateCalendarEventById with the required logic for this service method.
	// Add api_calendar_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Event{}) or use other options such as http.Ok ...
	// return Response(200, Event{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	// return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateCalendarEventById method not implemented")
}

// DeleteCalendarEventById - Delete Calendar Event by id.
func (s *CalendarEventsAPIService) DeleteCalendarEventById(ctx context.Context, calendarEventId string) (ImplResponse, error) {
	// TODO - update DeleteCalendarEventById with the required logic for this service method.
	// Add api_calendar_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	// return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteCalendarEventById method not implemented")
}
