// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Calendar - OpenAPI 3.0
 *
 * This is a sample Calendar Server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.12
 */

package api

import (
	"time"
)

type Event struct {
	EventId string `json:"event_id,omitempty"`

	Title string `json:"title,omitempty"`

	DateStart time.Time `json:"date_start,omitempty"`

	DateEnd time.Time `json:"date_end,omitempty"`

	Description string `json:"description,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	EventNotifyTime int32 `json:"event_notify_time,omitempty"`
}

// AssertEventRequired checks if the required fields are not zero-ed
func AssertEventRequired(obj Event) error {
	return nil
}

// AssertEventConstraints checks if the values respects the defined constraints
func AssertEventConstraints(obj Event) error {
	return nil
}
