logger:
  level: "INFO"
  file:
    enabled: true
    destination:
      - "./log/"
      - "./"
  stdout:
    enabled: true
  remote:
    enabled: false

storage_type: "postgres"
postgres:
  host: "localhost"
  port: 5432
  database: "postgres_db"
  username: "postgres_user"
  password: "postgres_password"
  schema: "calendar"

