postgres:
  host: "192.168.0.13"
  port: 5432
  database: "postgres_db"
  username: "postgres_user"
  password: "postgres_password"
  schema: "calendar"
broker:
  brokers_url: "kafka:9092"
  topic: "calendar-command"
  interval:
  group_id:
